### ISSUE TITLE
 :tzdata_release_updater terminating. 2nd argument: not a tuple

### ISSUE THREAD

**Issue by instancer-kirik** [lau/tzdata#148]
```
[debug] Tzdata data downloaded. Release version 2024b.
[error] GenServer :tzdata_release_updater terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :error)
    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Last message: :check_if_time_to_update
State: []
```
I did start off with my config as 
`config :tzdata, :data_dir, "priv/tzdata"`
which also had this error on mix phx.server
and is now 
```
config :tzdata, :autoupdate, :disabled # Disable automatic updates of tzdata because crashy
config :elixir, :time_zone_database, Tzdata.TimeZoneDatabase
config :tzdata, :data_dir, "priv/tzdata"
```

**Comment by treshenry** [comment]
Yep, just saw the same after updating.

```
[error] GenServer :tzdata_release_updater terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :error)
    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
```

**Comment by namxam** [comment]
It seems this have been an issue which is marked as resolved, but isn't. From what I understood by a quick glance, the source data might have changed and causes issues. #143

**Comment by lau** [comment]
@namxam Is this after upgrading to tzdata v1.1.2 ?

**Comment by namxam** [comment]
Honestly I don't know, because the error is handled gracefully. I just noticed it in a project I am not working on often. I know I updated a few dependencies but I am not sure if tzdata was among it. I will check when I am back at my computer.

**Comment by barttenbrinke** [comment]
Was greeted with the same error this morning, Upgrading from  tzdata 1.1.1 => 1.1.2 fixed this for me.

**Comment by chauhan471** [comment]
> Was greeted with the same error this morning, Upgrading from tzdata 1.1.1 => 1.1.2 fixed this for me.

Thanks it saved me some time.

**Comment by treshenry** [comment]
I think the tzdata dep in our project is actually coming from here: https://github.com/bitwalker/timex/blob/c45b9a734074ac2a56355ec52ebf931b932223b7/mix.exs#L58. Our lock file says 1.1.1 so I'll update and see if that resolves it.

**Comment by lau** [comment]
This should be fixed in the v1.1.2 release: https://github.com/lau/tzdata/commit/e63fc28c02d79dec9ea56e6cecf721f595a18495

**Comment by treshenry** [comment]
Woot!
<img width="674" alt="image" src="https://github.com/user-attachments/assets/0dae1a67-196d-4c95-a8f0-6ddb43d153da">

**Comment by hebbo** [comment]
anyone else still seeing this error even after updating to 1.1.2?

**Comment by treshenry** [comment]
You shouldn't be seeing this error as of 1.1.2. Check and make sure your mix.lock is showing `:tzdata, "1.1.2"` in case you had some sort of dep shenanigans @hebbo.

**Comment by hebbo** [comment]
> You shouldn't be seeing this error as of 1.1.2. Check and make sure your mix.lock is showing `:tzdata, "1.1.2"` in case you had some sort of dep shenanigans @hebbo.

Thanks @treshenry you are right. After writing the post we realised we actually never deployed the update in Production. False alarm.
